### ISSUE TITLE
Broke windows support

### ISSUE THREAD

**Issue by mcollina** [seriousme/openapi-schema-validator#167]
https://github.com/seriousme/openapi-schema-validator/commit/0e3460475147fa3432129c6c3076f6894245c7b4 broke this module on Windows

Consider

```js
import { fileURLToPath } from "node:url";

function localFile1(fileName) {
	return fileURLToPath(new URL(fileName, import.meta.url));
}

function localFile2(file) {
	return new URL(file, import.meta.url).pathname;
}

console.log('fileURLToPath', localFile1('./index.js'))
console.log('new URL', localFile2('./index.js'))
```

This prints:

```
fileURLToPath C:\Users\matteo\Repositories\openapi-schema-validator\index.js
new URL /C:/Users/matteo/Repositories/openapi-schema-validator/index.js
```

@seriousme can you issue a quick revert?

**Comment by seriousme** [comment]
@mcollina 

The added windows builds have rather flaky results. 
E.g.: 

https://github.com/seriousme/openapi-schema-validator/actions/runs/11831517981
Succeeds on all ubuntu, on windows for node and lts, but not on windows for lts-1 because it suddenly can't find `'D:\a\openapi-schema-validator\openapi-schema-validator\test\test-*.js'` which it can find perfectly on node and lts.

This is just not workable.

Any advice on how to fix this?

Kind regards,
Hans

**Comment by mcollina** [comment]
I've tried as well but I couldn't get them to select the right tests on Windows. I would need to research this a bit more.

I have a written https://github.com/mcollina/borp to work around these issues of node:test, but I couldn't get it to work either with that pattern (I name tests as `.test.js`).

I'll try to take a look asap and report back.

**Comment by seriousme** [comment]
The weird thing is that on some builds Windows + Node current( instead of LTS) also fails while on others it works which gave me the impression that its not a nodejs problem but a github Windows action runner problem.

**Comment by seriousme** [comment]
I just tried renaming the test to *.test.js but that doesn't work either:

```
> c8 node --test test/*.test.js

Could not find 'D:\a\openapi-schema-validator\openapi-schema-validator\test\*.test.js'
```

I also tried removing c8, but the same error pops up.
