### ISSUE TITLE
AJV validating URL properties as format `uri-reference`?

### ISSUE THREAD

**Issue by MikeRalphson** [seriousme/openapi-schema-validator#94]
See https://github.com/seriousme/openapi-schema-validator/blob/master/test/realworld/failed.md#api-discourselocal-version-latest

The linked schema has no `format` keyword, but `ajv` is complaining that `servers.url` should be a `uri-reference`. This looks incorrect as the appropriate `format` would be `uri-template` (though I'm not sure which Draft of JSON Schema introduced that `format` value).

**Comment by seriousme** [comment]
Hi,

I did some research:

There has apparantly been a change between 3.0 and 3.1 of the specification:
3.0 describes it as:
https://github.com/seriousme/openapi-schema-validator/blob/a400a7fdc0b3007a8aa3b590023adac576c2114d/schemas/v3.0/schema.json#L140-L148

See also: https://spec.openapis.org/oas/v3.0.3#server-object

3.1 describes it as :
https://github.com/seriousme/openapi-schema-validator/blob/d62b397f5ca0cf9f2cd81473ef749d56c33b899e/schemas/v3.1/schema.json#L165-L172

See also: https://spec.openapis.org/oas/v3.1.0#server-object

It seems like the OpenAPI team have decided to apply more strict rules on this object.

And since the spec at https://github.com/APIs-guru/openapi-directory/blob/main/APIs/discourse.local/latest/openapi.yaml starts with `openapi: 3.1.0` the test script applies the 3.1 schema.

Looking at the 'blame' of the 3.1 schema: https://github.com/OAI/OpenAPI-Specification/blame/main/schemas/v3.1/schema.json#L171

it seems that this tightening of the rules was introduced by:  https://github.com/OAI/OpenAPI-Specification/pull/2586

Hope this helps !

Kind regards,
Hans

**Comment by MikeRalphson** [comment]
Thanks. `failed.md` states it is OAS 3.0.3 though...

**Comment by seriousme** [comment]
Ok, just updated my script. It now doesn't take the openapiVer from https://api.apis.guru/v2/list.json anymore but reads the version from the file.

Hope this reduces confusion ;-)

Kind regards,
Hans

**Comment by MikeRalphson** [comment]
And I've fixed the bug and incorrect metadata on my side.

**Comment by MikeRalphson** [comment]
See https://github.com/OAI/OpenAPI-Specification/pull/3235

**Comment by seriousme** [comment]
As soon as the new version is available I will publish a new release. Good to see you fixed it at the source 👍

**Comment by seriousme** [comment]
@nielthiart thanks for the tip!

Good to see this one has been adressed. Unfortunately it looks like the YAML file and the  JSON file are modified by different PR's so its unclear to me if they represent the same data, can you confirm ?
(I converted the YAML to JSON and ran a diff and got some differences, not sure if they are semanticly different)

The header is still:
`"$id": "https://spec.openapis.org/oas/3.1/schema/2022-10-07",
is this correct?

Kind regards,
Hans

**Comment by nielthiart** [comment]
Hi Hans, yes it looks like the spec ID hasn't changed, so this update isn't released yet.

In the meanwhile, would you consider accepting a PR that brings this validation library in line with the specification, similar to how you currently replace $dynamicRefs by normal $refs?

The OAS project [reminds](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/README.md?plain=1#L6) validation libraries to treat the released text Specification as authoritative in the case of conflicts with the JSON schema:

> As a reminder, the JSON Schema is not the source of truth for the Specification. In cases of conflicts between the Specification itself and the JSON Schema, the Specification wins.

The text Specification [allows unformatted strings in server URLs](https://github.com/OAI/OpenAPI-Specification/blob/6f386968654fd483720aba0177e618e87a5d612d/versions/3.1.0.md?plain=1#L329C32-L329C38), which would validate URLs with template strings in.

**Comment by seriousme** [comment]
Niel, 

I'd rather wait for the official release as it seems nearly ready.
By making a separate copy we might get challenges when other official schema spec changes are released.

If you want to speed things up then getting OAS to publish their new schema seems the best course of action to me.

Kind regards,
Hans
